# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-28 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblDoc_kind',
            fields=[
                ('Doc_kindid_tblDoc_kind', models.AutoField(primary_key=True, serialize=False)),
                ('Doc_kind_name_tblDoc_kind', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='tbldoc',
            name='Doc_kindid_tblDoc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tblDoc_kind', to='quotation.tblDoc_kind'),
            preserve_default=False,
        ),
    ]
