# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-17 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_tblcompanies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcompanies',
            name='companyname_tblcompanies',
            field=models.CharField(default='ss', max_length=200),
        ),
    ]
