# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_auto_20181028_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldoc',
            name='Doc_kindid_tblDoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tblDoc_kin', to='quotation.tblDoc_kind'),
        ),
    ]
