# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_auto_20181029_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldoc_details',
            name='firstnum_tblDoc_details',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tbldoc_details',
            name='fourthnum_order_tblDoc_details',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tbldoc_details',
            name='secondnum_tblDoc_details',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tbldoc_details',
            name='thirdnum_tblDoc_details',
            field=models.IntegerField(default=0),
        ),
    ]
