# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_auto_20181029_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbldoc_details',
            old_name='fourthnum_order_tblDoc_details',
            new_name='fourthnum_tblDoc_details',
        ),
    ]
