# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_tbldoc_contactid_tbldoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldoc_details',
            name='creationtime_tblDoc_details',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
