# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-14 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbltest',
            fields=[
                ('Companyid_tblCompanies', models.AutoField(primary_key=True, serialize=False)),
                ('companyname_tblcompanies', models.CharField(default='ss', max_length=200)),
            ],
        ),
    ]
