# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('Doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
