# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_doc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc',
            old_name='Doc_id',
            new_name='Doc_id_tblDoc',
        ),
        migrations.RenameField(
            model_name='doc',
            old_name='address',
            new_name='address_tblDoc',
        ),
    ]
