# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181009_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='PCD_tblDoc',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
