# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_doc_pcd_tbldoc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc',
            old_name='Doc_id_tblDoc',
            new_name='Docid_tblDoc',
        ),
        migrations.RenameField(
            model_name='doc',
            old_name='PCD_tblDoc',
            new_name='Pcd_tblDoc',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='address_tblDoc',
        ),
    ]
