# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_doc_town_tbldoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_details',
            fields=[
                ('Doc_detailsid_tblDoc_details', models.AutoField(primary_key=True, serialize=False)),
                ('Docid_tblDoc_details', models.IntegerField(default=200)),
                ('Qty_tblDoc_details', models.IntegerField(default=200)),
            ],
        ),
    ]
