# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_doc_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_details',
            name='Docid_tblDoc_details',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='doc_details',
            name='Qty_tblDoc_details',
            field=models.IntegerField(default=1),
        ),
    ]
