# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181011_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_details',
            name='Docid_tblDoc_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Docreszletei', to='blog.Doc'),
        ),
    ]
