# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-07 10:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tblIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tblIssue', models.CharField(max_length=200)),
                ('text_tblIssue', models.TextField()),
                ('created_tblIssue', models.DateTimeField(default=django.utils.timezone.now)),
                ('author_tblIssue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
